import React, { useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Login from '../components/Login'
import Signup from '../components/Signup'
import 'semantic-ui-css/semantic.min.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState("true");

  function handleLogIn() {
    setIsLoggedIn(true)
  }

  return (
    <>
      <Head>
        <title>Mood Playlist Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoggedIn ? 
      <Login 
      isLoggedIn={isLoggedIn}/> :
      <Signup 
      onLogIn={handleLogIn}/>
    }
    </>
  )
}
