import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Login from '../components/Login'
import Signup from '../components/Signup'
import 'semantic-ui-css/semantic.min.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let isLoggedIn = true;
  return (
    <>
      <Head>
        <title>Mood Playlist Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoggedIn ? 
      <Login /> :
      <Signup />
    }
    </>
  )
}
